image: ruby:2.6

include:
  - component: gitlab.com/gitterra/GitTerra/gitterra@~latest

stages:
  - build
  - play

build:
  stage: build
  script: echo "Building this test repo, whie playing GitTerra in separate stage."
