name: Play GitTerra
run-name: Playing 🌎 GitTerra on ${{ github.repository }} 🗺️

on:
  push:
    branches:
      - main
jobs:
  play-gitterra:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, there!"
      - run: echo "Let's play GitTerra!"
      - run: echo "What are the files we're dealing with?"
      - run: find .
